language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
    - /opt/graalvm-ce-19.2.1
env:
  - GRAALVM_HOME=/opt/graalvm-ce-19.2.1
before_script:
  - ./install-graalvm.sh
install:
  - mvn -s settings.xml -q clean package -Pnative -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V
script:
  - mkdir target/dist
  - cp target/backend-proxy-1.0-SNAPSHOT-runner target/dist/application
  - cp -R $GRAALVM_HOME/jre/lib/amd64 target/dist/lib
  - cp $GRAALVM_HOME/jre/lib/security/cacerts target/dist/cacerts
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "jug-mz-quarkus"
  skip_cleanup: true
  local_dir: target/dist
  on:
    branch: master
